Attempt to fix missing workflows permission (#1196)
When pushing a tag we can something see an error like the following:

```
  /usr/bin/git push origin v0.5.16
  To https://github.com/mattdowdell/sandbox
   ! [remote rejected]   v0.5.16 -> v0.5.16 (refusing to allow a GitHub App to create or update workflow `.github/workflows/ci.yml` without `workflows` permission)
  error: failed to push some refs to 'https://github.com/mattdowdell/sandbox'
```

This appears to happen when an update is made by a non-human to a
workflow file. According to
https://github.com/orgs/community/discussions/35410, this can be fixed
by adding the `actions: write` permission (no such workflows permission
exists in gh actions).