Revert "Update sigstore/cosign-installer action to v4" (#626)
Reverts mattdowdell/sandbox#603 as it seems image signing no longer
works on `main`.

```
Run cosign sign --yes ${repository}:${version}@${digest}
  cosign sign --yes ${repository}:${version}@${digest}
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    repository: ghcr.io/mattdowdell/sandbox/example-rpc
    version: 0.2.76-0-g426d6fe
    digest: sha256:bd7c9ae0d540bbba490500b587e6f6670b511d1975618a3e29fb9de65ccb06c4
Signing artifact...
Error: signing [ghcr.io/mattdowdell/sandbox/example-rpc:0.2.76-0-g426d6fe@sha256:bd7c9ae0d540bbba490500b587e6f6670b511d1975618a3e29fb9de65ccb06c4]: signing digest: HEAD https://ghcr.io/v2/mattdowdell/sandbox/example-rpc/manifests/sha256:bd7c9ae0d540bbba490500b587e6f6670b511d1975618a3e29fb9de65ccb06c4: unexpected status code 404 Not Found (HEAD responses have no body, use GET for details)
error during command execution: signing [ghcr.io/mattdowdell/sandbox/example-rpc:0.2.76-0-g426d6fe@sha256:bd7c9ae0d540bbba490500b587e6f6670b511d1975618a3e29fb9de65ccb06c4]: signing digest: HEAD https://ghcr.io/v2/mattdowdell/sandbox/example-rpc/manifests/sha256:bd7c9ae0d540bbba490500b587e6f6670b511d1975618a3e29fb9de65ccb06c4: unexpected status code 404 Not Found (HEAD responses have no body, use GET for details)
Error: Process completed with exit code 1.
```

From
https://github.com/mattdowdell/sandbox/actions/runs/18848335206/job/53778911350